In [4]:
using DataFrames

In [5]:
using CSV

In [38]:
df = CSV.read("bank-marketing-campaign/bank-additional-full.csv")

41188×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 41    │ blue-collar │ married  │ unknown             │ unknown │
│ 9     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 10    │ 25    │ services    │ single   │ high.school         │ no      │
⋮
│ 41178 │ 57    │ retired     │ married  │ professional.course │ no      │
│ 41179 │ 62    │ retired     │ married  │ university.degree   │ no      │
│ 41180 │ 64    │ retired     │ divorced │ professional.course │ no      │
│ 41181 │ 36    │ admin.      │ married  │ university.degree   │ no      │
│ 41182 │ 37    │ admin.      │ married  │ university.degree   │ no      │
│ 41183 │ 29    │ unemployed  │ single   │ basic.4y            │ no      │
│ 41184 │ 73    │ retired     │ married  │ professional.course │ no      │
│ 41185 │ 46    │ blue-collar │ married  │ professional.course │ no      │
│ 41186 │ 56    │ retired     │ married  │ university.degree   │ no      │
│ 41187 │ 44    │ technician  │ married  │ professional.course │ no      │
│ 41188 │ 74    │ retired     │ married  │ professional.course │ no      │

# Final task: Predict Y

## Task 1 - Data cleaning and preparation

In [39]:
# convert dataset into a matrix
df = convert(Matrix,df)

41188×21 Array{Any,2}:
 56  "housemaid"    "married"   …  93.994  -36.4  4.857  5191.0  "no" 
 57  "services"     "married"      93.994  -36.4  4.857  5191.0  "no" 
 37  "services"     "married"      93.994  -36.4  4.857  5191.0  "no" 
 40  "admin."       "married"      93.994  -36.4  4.857  5191.0  "no" 
 56  "services"     "married"      93.994  -36.4  4.857  5191.0  "no" 
 45  "services"     "married"   …  93.994  -36.4  4.857  5191.0  "no" 
 59  "admin."       "married"      93.994  -36.4  4.857  5191.0  "no" 
 41  "blue-collar"  "married"      93.994  -36.4  4.857  5191.0  "no" 
 24  "technician"   "single"       93.994  -36.4  4.857  5191.0  "no" 
 25  "services"     "single"       93.994  -36.4  4.857  5191.0  "no" 
 41  "blue-collar"  "married"   …  93.994  -36.4  4.857  5191.0  "no" 
 25  "services"     "single"       93.994  -36.4  4.857  5191.0  "no" 
 29  "blue-collar"  "single"       93.994  -36.4  4.857  5191.0  "no" 
  ⋮                             ⋱                     

In [11]:
# get the list of possible values
function pValues(column)
    values = []
    count = 0
    for c in column
        for v in values
            if(c == v)
                count = 1 + count
            end
        end
        if(count == 0)
            push!(values,c)
        end
        count = 0
    end
    return values
end        
    

pValues (generic function with 1 method)

In [12]:
# change strings to number
function categoricalData(column,values)
    for c in 1:size(column,1)
        for i in 1:size(values,1)
            if(column[c] == values[i])
                column[c] = i
            end
        end
    end
    return column
end
                

categoricalData (generic function with 1 method)

In [13]:
# binary data
function binaryData(column)
    for i in 1:size(column,1)
        if(column[i] == "yes")
            column[i] = 1
        else
            column[i] = 0
        end
    end
    return column
end

binaryData (generic function with 1 method)

In [40]:
# prepare job description
df[:,2] = categoricalData(df[:,2], pValues(df[:,2]))
# prepare marital status
df[:,3] = categoricalData(df[:,3], pValues(df[:,3]))
# prepare education
df[:,4] = categoricalData(df[:,4], pValues(df[:,4]))
# prepare default
df[:,5] = categoricalData(df[:,5], pValues(df[:,5]))
# prepare housing
df[:,6] = categoricalData(df[:,6], pValues(df[:,6]))
# prepare loan
df[:,7] = categoricalData(df[:,7], pValues(df[:,7]))
# prepare contact
df[:,8] = categoricalData(df[:,8], pValues(df[:,8]))
# prepare month
df[:,9] = categoricalData(df[:,9], pValues(df[:,9]))
# prepare day of week
df[:,10] = categoricalData(df[:,10], pValues(df[:,10]))
# prepare poutcome
df[:,15] = categoricalData(df[:,15], pValues(df[:,15]))

# prepare y
df[:,21] = binaryData(df[:,21])

41188-element Array{Any,1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 1
 0
 0
 1
 0
 1
 0
 0
 1
 0

In [41]:
# convert matrix to Array float
df = convert(Array{Float64},df)

41188×21 Array{Float64,2}:
 56.0  1.0  1.0  1.0  1.0  1.0  1.0  …  93.994  -36.4  4.857  5191.0  0.0
 57.0  2.0  1.0  2.0  2.0  1.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 37.0  2.0  1.0  2.0  1.0  2.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 40.0  3.0  1.0  3.0  1.0  1.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 56.0  2.0  1.0  2.0  1.0  1.0  2.0     93.994  -36.4  4.857  5191.0  0.0
 45.0  2.0  1.0  4.0  2.0  1.0  1.0  …  93.994  -36.4  4.857  5191.0  0.0
 59.0  3.0  1.0  5.0  1.0  1.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 41.0  4.0  1.0  6.0  2.0  1.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 24.0  5.0  2.0  5.0  1.0  2.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 25.0  2.0  2.0  2.0  1.0  2.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 41.0  4.0  1.0  6.0  2.0  1.0  1.0  …  93.994  -36.4  4.857  5191.0  0.0
 25.0  2.0  2.0  2.0  1.0  2.0  1.0     93.994  -36.4  4.857  5191.0  0.0
 29.0  4.0  2.0  2.0  1.0  1.0  2.0     93.994  -36.4  4.857  5191.0  0.0
  ⋮        

## Task 2 - 80/20 divisision, standardization, oneMatrix, theta

In [43]:
# x and y
x = df[:,1:20]
y = df[:,21]
# satandardize the x
using StatsBase
dt = fit(ZScoreTransform, x, dims=2)
x = StatsBase.transform(dt,x)

41188×20 Array{Float64,2}:
 -0.234071  -0.281215  -0.281215  -0.281215  …  -0.313273  -0.277909  4.16744
 -0.228476  -0.275597  -0.276454  -0.275597     -0.308497  -0.27315   4.17008
 -0.248101  -0.278093  -0.27895   -0.278093     -0.310999  -0.275645  4.16845
 -0.242404  -0.274099  -0.275812  -0.274099     -0.307849  -0.272508  4.17004
 -0.2362    -0.282492  -0.283349  -0.282492     -0.315411  -0.280043  4.16585
 -0.240472  -0.277319  -0.278176  -0.275605  …  -0.310224  -0.274871  4.16918
 -0.226546  -0.274523  -0.276237  -0.27281      -0.308279  -0.272932  4.17025
 -0.244737  -0.276445  -0.279016  -0.274731     -0.311067  -0.275711  4.16875
 -0.265609  -0.281892  -0.284463  -0.281892     -0.317372  -0.282014  4.16253
 -0.250029  -0.269711  -0.269711  -0.269711     -0.302572  -0.267266  4.17074
 -0.237518  -0.269189  -0.271757  -0.267477  …  -0.303771  -0.268456  4.17083
 -0.257705  -0.277412  -0.277412  -0.277412     -0.310313  -0.274964  4.16851
 -0.250793  -0.272204  -0.273917  -0.

In [59]:
# ones matrix
oneMatrix = ones(size(x,1))
x = hcat(x,oneMatrix)
# theta
theta = zeros(size(x,2))

22-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [60]:
# 80% for training and 20 % for testing
i = size(x,1)
x_train = x[1:trunc(Int,i * 0.8),:]
x_test = x[trunc(Int,i * 0.8)+1:i,:]

y_train = y[1:trunc(Int,i * 0.8),:]
y_test = y[trunc(Int,i * 0.8)+1:i,:]

8238×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0